# Numpy Task

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

# Creating Array

In [4]:
my_list_numbers = [1,2,3,4,5,6,7,8]
my_list_numbers

[1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
type(my_list_numbers) # It is in List formate

list

In [6]:
my_array_numbers = np.array(my_list_numbers)
my_array_numbers # Now its converted into array formate

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
type(my_array_numbers) 

numpy.ndarray

In [8]:
# Now we learn Built-in Important function of numpy

In [9]:
np.arange(15) # np.arange(15) - Creates a NumPy array of values from 0 to 14.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.arange(3.0)

array([0., 1., 2.])

In [12]:
# np.arange(start, stop, step)
np.arange(1,9) # Creates a NumPy array of values from 1 to 8.

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10) # always 1st arg < 2nd arg Its give empty array

array([], dtype=int64)

In [16]:
np.arange(-20,10) # Its start from -20 and goes till 9, the last number 10 is excluse

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-16,36)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
        10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35])

In [18]:
arr = np.arange(-35,51)
arr # Same scenerio is there starts from -35 and goes till 50

array([-35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23,
       -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,
        -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,
         4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50])

In [19]:
np.arange(10,95,5) # 10- starting from 95- end point 5 - step count

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90])

In [20]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [21]:
np.zeros(5) # parameter tunning (By default system gives in float data type)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(5,dtype=int) # Hyperparameter tunning (User change the data type into other rather is string,complex,int)

array([0, 0, 0, 0, 0])

In [23]:
np.zeros(5,dtype=complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [24]:
np.zeros(3) # Creates a NumPy array containing 3 zeros.

array([0., 0., 0.])

In [25]:
np.zeros((2,2), dtype=int)
# np.zeros((2, 2), dtype=int) - Creates a 2×2 NumPy array filled with zeros using integer data type.

array([[0, 0],
       [0, 0]])

In [26]:
zero = np.zeros([2, 2])
print(zero)      # Prints the NumPy array
type(zero)       # Returns the data type of the variable (numpy.ndarray)

[[0. 0.]
 [0. 0.]]


numpy.ndarray

In [27]:
zero = np.zeros([3,3], dtype=int)
print(zero)
print('#####')
print(type(zero))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
#####
<class 'numpy.ndarray'>


In [28]:
np.zeros((2,10), dtype=int) # Creates a 2×10 NumPy array filled with integer zeros.

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [30]:
np.zeros((5,3), dtype=int) # By default 1st Argument -- will give row & 2nd Argument - columns

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
n = np.zeros((3,2), dtype=int)
n2 = np.zeros((2,3), dtype=int)
print(n,'\n')
print(n2)

[[0 0]
 [0 0]
 [0 0]] 

[[0 0 0]
 [0 0 0]]


In [32]:
# Tuple (6, 7) defines the shape of the NumPy array.
num = (6, 7)

# np.zeros() creates a 6×7 NumPy array filled with integer zeros.
print(np.zeros(num, dtype=int),'\n')
print(type(num))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 

<class 'tuple'>


In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
np.ones((5,4), dtype=int) # By default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
print(num, '\n') # Prints the shape stored in the 'num' variable.
print(np.ones(num, dtype=int))

(6, 7) 

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [38]:
np.random.rand(3) # Generates a 1D NumPy array containing 3 random values between 0 and 1.

array([0.13949594, 0.52173801, 0.36078605])

In [39]:
np.random.rand(1) # Generates a 1D NumPy array containing 1 random values between 0 and 1.

array([0.19969737])

In [40]:
np.random.rand(3,3) # Generates a 3×3 NumPy array containing random values between 0 and 1.

array([[0.02223849, 0.4076936 , 0.81470335],
       [0.34092465, 0.96009562, 0.20435652],
       [0.16127461, 0.90745088, 0.67052448]])

In [41]:
# Defines the shape of the NumPy array as 3 rows and 3 columns.
num_set = (3,3)

# Defines the shape of the NumPy array as 3 rows and 3 columns.
print(np.random.rand(*num_set))

[[0.02290208 0.07278903 0.53255941]
 [0.50943584 0.51716924 0.15760039]
 [0.15442936 0.53432958 0.84713641]]


In [42]:
# randint(start,end,size)
np.random.randint(1,101)

51

In [43]:
np.random.randint(1,100,5) # Basically 5 random integers between 1 to 99 

array([27, 84, 60, 57, 90], dtype=int32)

In [44]:
np.random.randint(1,21) # It give 1 integer between 1 to 20

6

In [45]:
np.random.randint(10,20,2) # Generate 2 random integers between 10 to 19.

array([19, 11], dtype=int32)

In [46]:
np.random.randint(1,51,(5,5)) # Generates a 5×5 NumPy matrix with random integers between 1 and 50.

array([[49, 48, 27,  4, 31],
       [19,  9, 13, 12, 11],
       [26, 32, 20,  7, 20],
       [44, 48, 36, 43,  7],
       [44, 43, 26, 20,  5]], dtype=int32)

In [47]:
np.random.randint(1,100,(12,12)) # Generate 12x12 matrix and element range is between (1 to 99)

array([[22, 60, 41, 81, 50, 39, 31, 48, 33, 98, 35,  7],
       [24, 69, 69, 54, 23, 68, 97, 98, 48, 43, 41, 57],
       [16,  7, 49, 61, 46, 39,  1, 10, 81, 39, 70, 87],
       [91, 94, 68, 49, 93, 95, 83,  8, 99, 68, 47, 90],
       [87, 81, 35,  1, 22, 36, 87, 73, 91, 70, 80, 77],
       [48, 53, 10, 83, 63, 73, 33, 87, 89, 88, 32, 44],
       [32, 24, 88,  9, 59, 97, 62,  6, 72, 19, 52, 78],
       [53, 77, 47,  1, 54, 98, 46, 61,  9, 44, 19, 68],
       [29, 51, 31, 64, 41, 47, 14, 56, 87,  3, 99, 85],
       [49, 26, 65, 87, 71, 34, 45, 95, 70, 90, 15, 51],
       [63, 22, 46, 65, 17, 77, 72, 44, 14, 78, 15, 93],
       [64, 96, 63, 73, 40, 60, 42, 53, 86, 35, 77, 53]], dtype=int32)

In [48]:
# np.arange(1, 16) creates an array of values from 1 to 15.
# reshape(5, 3) reshapes the array into a 5×3 matrix.
np.arange(1, 16).reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [49]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [50]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 10, 15, 12],
       [19, 18, 13, 19],
       [15, 14, 16, 17],
       [17, 17, 18, 11],
       [11, 10, 17, 18]], dtype=int32)

In [51]:
type(b)

numpy.ndarray

In [52]:
b[:]

array([[12, 10, 15, 12],
       [19, 18, 13, 19],
       [15, 14, 16, 17],
       [17, 17, 18, 11],
       [11, 10, 17, 18]], dtype=int32)

In [53]:
b[1:3]
# Selects rows from index 1 to 2 (index 3 is excluded) and includes all columns

array([[19, 18, 13, 19],
       [15, 14, 16, 17]], dtype=int32)

In [54]:
b

array([[12, 10, 15, 12],
       [19, 18, 13, 19],
       [15, 14, 16, 17],
       [17, 17, 18, 11],
       [11, 10, 17, 18]], dtype=int32)

In [55]:
b[1,2]
# Accesses the element at row index 1 and column index 2.

np.int32(13)

In [56]:
b[1,3]

np.int32(19)

In [57]:
b

array([[12, 10, 15, 12],
       [19, 18, 13, 19],
       [15, 14, 16, 17],
       [17, 17, 18, 11],
       [11, 10, 17, 18]], dtype=int32)

In [58]:
b[1,-1]

np.int32(19)

In [59]:
b[2:3]

array([[15, 14, 16, 17]], dtype=int32)

In [60]:
# Selects rows from index 0 to 4 and columns from index 0 to 1.
print(b[0:5, 0:2])

[[12 10]
 [19 18]
 [15 14]
 [17 17]
 [11 10]]


In [61]:
print(b,'\n')
print(b[0:-2])


[[12 10 15 12]
 [19 18 13 19]
 [15 14 16 17]
 [17 17 18 11]
 [11 10 17 18]] 

[[12 10 15 12]
 [19 18 13 19]
 [15 14 16 17]]


In [62]:
b[0:5,0:1]
# Selects all 5 rows and the first column from the NumPy array.

array([[12],
       [19],
       [15],
       [17],
       [11]], dtype=int32)

In [63]:
b[-5,-2]

np.int32(15)

In [64]:
print(b,'\n')
print(b[-4:2])

[[12 10 15 12]
 [19 18 13 19]
 [15 14 16 17]
 [17 17 18 11]
 [11 10 17 18]] 

[[19 18 13 19]]


In [65]:
arr = np.random.randint(1,100,(10,10))

In [66]:
arr[:]

array([[89, 49, 31, 11, 54, 70, 35, 70, 99, 14],
       [48, 58, 58, 83,  9, 90, 81, 68, 95, 75],
       [27, 20, 50,  8, 88, 39,  2, 20, 86, 70],
       [62, 35, 68,  6, 84,  9, 13, 69, 50, 34],
       [41, 82, 38, 21, 48, 37, 25, 61, 85, 58],
       [12,  8, 11, 98, 90, 57, 62, 55, 86, 26],
       [87, 18, 45, 62, 26, 65, 72, 33, 61, 33],
       [14, 40,  1, 77, 69, 12, 71,  8,  8, 70],
       [36, 42, 47, 26, 38, 90, 31, 16,  9, 83],
       [46, 82, 60, 52, 23,  6, 60, 38, 13, 75]], dtype=int32)

In [67]:
arr[:4]

array([[89, 49, 31, 11, 54, 70, 35, 70, 99, 14],
       [48, 58, 58, 83,  9, 90, 81, 68, 95, 75],
       [27, 20, 50,  8, 88, 39,  2, 20, 86, 70],
       [62, 35, 68,  6, 84,  9, 13, 69, 50, 34]], dtype=int32)

In [68]:
print(arr[0:5])

[[89 49 31 11 54 70 35 70 99 14]
 [48 58 58 83  9 90 81 68 95 75]
 [27 20 50  8 88 39  2 20 86 70]
 [62 35 68  6 84  9 13 69 50 34]
 [41 82 38 21 48 37 25 61 85 58]]


In [69]:
arr[1,4]

np.int32(9)

In [70]:
arr[-5,5]

np.int32(57)

In [71]:
arr[-5,-5]

np.int32(57)

In [72]:
arr[::-1]

array([[46, 82, 60, 52, 23,  6, 60, 38, 13, 75],
       [36, 42, 47, 26, 38, 90, 31, 16,  9, 83],
       [14, 40,  1, 77, 69, 12, 71,  8,  8, 70],
       [87, 18, 45, 62, 26, 65, 72, 33, 61, 33],
       [12,  8, 11, 98, 90, 57, 62, 55, 86, 26],
       [41, 82, 38, 21, 48, 37, 25, 61, 85, 58],
       [62, 35, 68,  6, 84,  9, 13, 69, 50, 34],
       [27, 20, 50,  8, 88, 39,  2, 20, 86, 70],
       [48, 58, 58, 83,  9, 90, 81, 68, 95, 75],
       [89, 49, 31, 11, 54, 70, 35, 70, 99, 14]], dtype=int32)

In [73]:
arr[::-2]

array([[46, 82, 60, 52, 23,  6, 60, 38, 13, 75],
       [14, 40,  1, 77, 69, 12, 71,  8,  8, 70],
       [12,  8, 11, 98, 90, 57, 62, 55, 86, 26],
       [62, 35, 68,  6, 84,  9, 13, 69, 50, 34],
       [48, 58, 58, 83,  9, 90, 81, 68, 95, 75]], dtype=int32)

In [74]:
arr.min()
# Returns the minimum (smallest) value present in the NumPy array.

np.int32(1)

In [75]:
arr.max()
# Returns the minimum (Largest) value present in the NumPy array.

np.int32(99)

In [76]:
arr.mean()
# Returns the mean (Average) value of all element in the NumPy array.

np.float64(47.73)