# Without work on import* we can find Median, Mode

In [1]:
import numpy as np

In [3]:
arr = np.array([0,1,2,3,4,5,6,7,8])

In [5]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
arr.reshape(9,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [11]:
arr2 = np.array([0,1,2,3,4,5])
arr2

array([0, 1, 2, 3, 4, 5])

In [12]:
arr2.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
arr2.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
print(arr.reshape(3,3,order='C'))
print(arr.reshape(3,3,order='F'))
print(arr.reshape(3,3,order='A'))
# order='C' -> Elements are arranged row-wise (C-style order)
# order='F' -> Elements are arranged column-wise (Fortran-style order)
# order='A' -> Automatically chooses C or F order based on array memory layout

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
arr2.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [30]:
mat = np.random.randint(1,100,(10,10))
mat

array([[70,  2, 68, 75,  3, 97, 42,  4, 95, 80],
       [29,  9, 78, 99, 76, 30, 10, 36, 82, 54],
       [83, 69,  9, 56, 73, 76, 82, 33, 59, 15],
       [91, 94, 43, 43, 37, 20, 49, 49, 66, 12],
       [96, 55, 18, 72, 53, 47, 16, 15,  3, 45],
       [97, 93, 79, 29, 65, 77, 24, 91, 75, 16],
       [57, 61, 84,  5, 20, 50, 87, 30, 46, 38],
       [14, 86, 58, 55, 60, 41, 88, 96, 59, 94],
       [53, 92, 50, 12, 29,  6, 44, 15, 43,  4],
       [37, 80, 76, 53, 17, 36, 45, 33, 24, 70]], dtype=int32)

In [31]:
mat[4,5]

np.int32(47)

In [32]:
mat[:4,:5]

array([[70,  2, 68, 75,  3],
       [29,  9, 78, 99, 76],
       [83, 69,  9, 56, 73],
       [91, 94, 43, 43, 37]], dtype=int32)

In [ ]:
mat[0:4] # Return 0 to 3 index rows, 4th row is excluded

array([[70,  2, 68, 75,  3, 97, 42,  4, 95, 80],
       [29,  9, 78, 99, 76, 30, 10, 36, 82, 54],
       [83, 69,  9, 56, 73, 76, 82, 33, 59, 15],
       [91, 94, 43, 43, 37, 20, 49, 49, 66, 12]], dtype=int32)

In [40]:
mat[:,0:4] # Return all rows but the column starts from 0 to 3rd column, 4th column is excluded

array([[70,  2, 68, 75],
       [29,  9, 78, 99],
       [83, 69,  9, 56],
       [91, 94, 43, 43],
       [96, 55, 18, 72],
       [97, 93, 79, 29],
       [57, 61, 84,  5],
       [14, 86, 58, 55],
       [53, 92, 50, 12],
       [37, 80, 76, 53]], dtype=int32)

In [ ]:
mat[mat<50] # Return only values Less then 50

array([ 2,  3, 42,  4, 29,  9, 30, 10, 36,  9, 33, 15, 43, 43, 37, 20, 49,
       49, 12, 18, 47, 16, 15,  3, 45, 29, 24, 16,  5, 20, 30, 46, 38, 14,
       41, 12, 29,  6, 44, 15, 43,  4, 37, 17, 36, 45, 33, 24],
      dtype=int32)

In [45]:
mat<50 # show Boolean action for each element of matrix which is actual greater then 50

array([[False,  True, False, False,  True, False,  True,  True, False,
        False],
       [ True,  True, False, False, False,  True,  True,  True, False,
        False],
       [False, False,  True, False, False, False, False,  True, False,
         True],
       [False, False,  True,  True,  True,  True,  True,  True, False,
         True],
       [False, False,  True, False, False,  True,  True,  True,  True,
         True],
       [False, False, False,  True, False, False,  True, False, False,
         True],
       [False, False, False,  True,  True, False, False,  True,  True,
         True],
       [ True, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False,  True,  True,  True,  True,  True,
        False]])

In [49]:
mat[mat>=50] # Return values Greater then 50 from np. nd Array

array([70, 68, 75, 97, 95, 80, 78, 99, 76, 82, 54, 83, 69, 56, 73, 76, 82,
       59, 91, 94, 66, 96, 55, 72, 53, 97, 93, 79, 65, 77, 91, 75, 57, 61,
       84, 50, 87, 86, 58, 55, 60, 88, 96, 59, 94, 53, 92, 50, 80, 76, 53,
       70], dtype=int32)

In [2]:
def Wish_Morning():
    print("GOOD MORNING EVERYONE")
def Wish_Afternoon():
    print("GOOD AFTERNOON EVERYONE")
def Wish_Evening():
    print("GOOD EVENING EVERYONE")
def Wish_Night():
    print("GOOD NIGHT! :)")
    
Wish_Morning()
Wish_Afternoon()
Wish_Evening()
Wish_Night()

GOOD MORNING EVERYONE
GOOD AFTERNOON EVERYONE
GOOD EVENING EVERYONE
GOOD NIGHT! :)


# OTP Generator

In [87]:
import random
def otp_generator(Length = 4):
    """Generate a numeric OTP of a specified length."""
    digits = "0123456789"
    otp = ''.join(random.choice(digits) for _ in range(Length))
    return otp
# Example usage:
otp_length = 6
otp = otp_generator(otp_length)
print(f'Your OTP is: {otp}')

Your OTP is: 109109
